### ISSUE TITLE
Parser issue

### ISSUE THREAD

**Issue by peterbsmith2** [MattFlood7/MediumBot#2]
Launching Chrome
Signing in...
Success!
```
Traceback (most recent call last):
  File "MediumBot.py", line 539, in <module>
    Launch()
  File "MediumBot.py", line 58, in Launch
    StartBrowser(1)
  File "MediumBot.py", line 85, in StartBrowser
    MediumBot(browser)
  File "MediumBot.py", line 231, in MediumBot
    tagURLsQueued = ScrapeUsersFavoriteTagsUrls(browser)
  File "MediumBot.py", line 274, in ScrapeUsersFavoriteTagsUrls
    soup = BeautifulSoup(browser.page_source, "lxml")
  File "/usr/local/lib/python2.7/site-packages/bs4/__init__.py", line 165, in __init__
    % ",".join(features))
bs4.FeatureNotFound: Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?
```

**Comment by MattFlood7** [comment]
Hey @peterbsmith2 just saw this. Will look into this when I get a chance. Still moving into the house.

**Comment by peterbsmith2** [comment]
Right on!

**Comment by MattFlood7** [comment]
Posting slack response for visibility:
Hey I may have a quick fix for you with the MediumBot. Looks like you don’t have lxml installed on your system. Use `pip install lxml` to install it. Once installed try the bot again and let me know how it goes.

**Comment by peterbsmith2** [comment]
worked!
